<?php

$foo = ( $bob ) ? 'dog' : 'cat';

$foo = ( $fruit)
       ? 'apple'
       : 'carrot';

$foo = ( $dave )
   ? 'robot'
   : 'human';

$foo = ( $dave )
       ? 'robot'
     : 'human';

$foo = ( $dave )
     ? 'robot'
       : 'human';

$foo = ( $dave )
        ? 'robot'
       : 'human';

$foo = ( $dave )
       ? 'robot'
        : 'human';

$foo = ( $dave )
        ? 'robot'
        : 'human';

$variable = ( $x == 1 ) ? ( ( $y == 2 ) ? true : false ) : false;

$foo = $fruit
       ? 'apple'
       : 'carrot';

$nextPtrCount = isset( $tokens[ $foo ]['nested_parenthesis'] )
                ? count( $tokens[ $foo ]['nested_parenthesis'] )
                : 0;

$foo = ( $dave )
? 'robot'
       : 'human';

$foo = ( $dave )
       ? 'robot'
: 'human';

return ( $bob )
       ? false
       : true;

return ( $bob )
        ? false
       : true;

return ( $bob )
       ? false
        : true;

$project_owner = 'something';

return ( $project_owner )
       ? false
       : true;


$info = [
    \Net_FeatureQueue_Site::TABLE_PREFIX_ . 'parent_id' => ( $category )
                                                           ? $category->id
                                                           : 0,
];

$info = [
    \Net_FeatureQueue_Site::TABLE_PREFIX_ . 'parent_id' => ( $category )
                                                            ? $category->id
                                                           : 0,
];

$info = [
    \Net_FeatureQueue_Site::TABLE_PREFIX_ . 'parent_id' => ( $category )
                                                           ? $category->id
                                                            : 0,
];
